apps/hospital/urls.py
from django.urls import path
from .views import (
    Home,
    HospitalListView, HospitalMapListView,
    DepartmentListView, DepartmentDetailView,
    DoctorListView, DoctorDetailView, hospital_detail
)

app_name = 'hospital'

urlpatterns = [
    # **Region URLs**
    path('home/', Home.as_view(), name='home'),
    path('hospital/', HospitalListView.as_view(), name='hospital_list'),
    path('hospital_map/', HospitalMapListView.as_view(), name='hospital_map_list'),
    path('hospital_detail/<slug:slug>/', hospital_detail, name='hospital_detail'),

    # **Hospital URLs**
    # path('hospitals/', HospitalListView.as_view(), name='hospital-list'),
    # path('hospitals/<int:pk>/', HospitalDetailView.as_view(), name='hospital-detail'),
    #
    # # **Department URLs**
    # path('departments/', DepartmentListView.as_view(), name='department-list'),
    # path('departments/<int:pk>/', DepartmentDetailView.as_view(), name='department-detail'),
    #
    # # **Doctor URLs**
    # path('doctors/', DoctorListView.as_view(), name='doctor-list'),
    # path('doctors/<int:pk>/', DoctorDetailView.as_view(), name='doctor-detail'),
]

apps/main/urls.py
from django.urls import path
# app_name = 'main'

# urlpatterns = [
#
# ]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('apps.main.urls', namespace='main')),
    path('', include('apps.hospital.urls', namespace='hospital'))

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/hospital/models.py
from django.utils.text import slugify
from django.utils import timezone
from django.db.models.signals import pre_save
from django.db import models

# Create your models here.
class Region(models.Model):
    name =  models.CharField(unique=True, max_length=123)

    def __str__(self):
        return self.name

class Hospital(models.Model):
    region = models.ForeignKey(Region, on_delete=models.CASCADE, related_name='hospital')
    name = models.CharField(max_length=255,)
    phone = models.CharField(max_length=20, blank=True, null=True)
    address = models.TextField()
    latitude = models.FloatField(blank=True, null=True)
    longitude = models.FloatField(blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    opening_hours = models.CharField(max_length=100, blank=True, null=True)
    slug = models.SlugField(unique=True, editable=False, null=True, blank=True, max_length=225)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class ImageHospital(models.Model):
    hospital = models.ForeignKey(Hospital, on_delete=models.CASCADE, related_name='hospital_image')
    image = models.ImageField(upload_to='hospital_logos/', blank=True, null=True)

    def __str__(self):
        return self.hospital.name

class Department(models.Model):
    hospital = models.ForeignKey(Hospital, on_delete=models.CASCADE, related_name='departments')
    name = models.CharField(max_length=123)

    def __str__(self):
        return f"{self.hospital.name} --> ({self.name})"


class Doctor(models.Model):
    hospital = models.ForeignKey(Hospital, on_delete=models.CASCADE, related_name='doctors')
    department = models.ForeignKey(Department, on_delete=models.SET_NULL, null=True, blank=True, related_name='doctors')
    name = models.CharField(max_length=123)
    specialty = models.CharField(max_length=123)
    phone = models.CharField(max_length=20, blank=True, null=True)
    opening_hours = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return f"Dr. {self.name} --> {self.specialty}"



def blog_pre_save(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.name + " - " + timezone.now().strftime('%Y-%m-%d %H:%M:%S.%f'))


pre_save.connect(blog_pre_save, sender=Hospital)

apps/main/models.py
from django.db import models

# Create your models here.

apps/hospital/forms.py
from django import forms
from .models import Region, Hospital, ImageHospital, Department, Doctor

class RegionForm(forms.ModelForm):
    class Meta:
        model = Region
        fields = '__all__'

class HospitalForm(forms.ModelForm):
    class Meta:
        model = Hospital
        fields = '__all__'

class ImageHospitalForm(forms.ModelForm):
    class Meta:
        model = ImageHospital
        fields = '__all__'

class DepartmentForm(forms.ModelForm):
    class Meta:
        model = Department
        fields = '__all__'

class DoctorForm(forms.ModelForm):
    class Meta:
        model = Doctor
        fields = '__all__'

apps/hospital/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView, View
from .models import Region, Hospital, Department, Doctor
from django.http import JsonResponse
from django.views.generic import TemplateView, CreateView
import json


class Home(TemplateView):
    template_name = 'index.html'


# **1. Region Views**
# class RegionListView(TemplateView):
#     template_name = 'navbar.html'
#
#     def get_context_data(self,  **kwargs):
#         cnt = super().get_context_data(**kwargs)
#         cnt['regions'] = Region.objects.order_by('id')
#         print("Regions:", cnt['regions'])
#         print('asassasaa')# Konsolga chiqarib ko‘rish
#         return cnt


# **2. Hospital Views**
class HospitalListView(View):
    template_name = 'blog.html'

    def get(self, request, *args, **kwargs):
        region_name = request.GET.get('region')

        if region_name:
            hospitals = Hospital.objects.filter(region__name=region_name)  # Faqat tanlangan regionni olish
        else:
            hospitals = Hospital.objects.all()

        ctx = {
            'hospitals': hospitals,
        }
        return render(request, 'blog.html', ctx)


def hospital_detail(request, slug):
    hospital = get_object_or_404(Hospital, slug=slug)
    context = {
        'hospital': hospital,

    }
    return render(request, 'single-blog.html', context)


# **3. Department Views**
class DepartmentListView(ListView):
    model = Department
    template_name = 'department_list.html'
    context_object_name = 'departments'


class DepartmentDetailView(DetailView):
    model = Department
    template_name = 'department_detail.html'
    context_object_name = 'department'


# **4. Doctor Views**
class DoctorListView(ListView):
    model = Doctor
    template_name = 'doctor_list.html'
    context_object_name = 'doctors'


class DoctorDetailView(DetailView):
    model = Doctor
    template_name = 'doctor_detail.html'
    context_object_name = 'doctor'


class HospitalMapListView(View):
    template_name = 'google_map.html'

    def get_center(self, hospitals):
        """Hospitallar orqali markazni aniqlash"""
        if hospitals.exists():
            first_hospital = hospitals.first()  # Birinchi hospital koordinatasini olish
            if first_hospital.latitude and first_hospital.longitude:
                return {"lat": first_hospital.latitude, "lng": first_hospital.longitude}

        return {"lat": 41.2995, "lng": 69.2401}

    def get(self, request, *args, **kwargs):
        region_name = request.GET.get('region')

        if region_name:
            hospitals = Hospital.objects.filter(region__name=region_name)  # Faqat tanlangan regionni olish
        else:
            hospitals = Hospital.objects.all()
        center = self.get_center(hospitals)  # Markazni aniqlash
        hospitals_data = list(hospitals.values('name', 'latitude', 'longitude', 'address'))  # JSON uchun ma'lumot
        ctx = {
            'map_center': json.dumps(center),  # Markazni JSON sifatida template-ga uzatamiz
            'hospitals_json': json.dumps(hospitals_data, ensure_ascii=False)  # JSON sifatida template-ga uzatamiz
        }
        return render(request, 'google_map.html', ctx)

apps/main/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <!-- Title  -->
    <title>MedLine </title>

    <!-- Favicon  -->
    <link rel="icon" href="{% static 'img/core-img/favicon.ico' %}">

    <!-- Style CSS -->
    <link rel="stylesheet" href="{% static 'styles/css/style.css' %}">

</head>
<body onload="initMap()">


{% if messages %}
	{% include 'messages.html' %}

{% else %}
    {% include 'navbar.html' %}
{% endif %}



{% block content %}



{% endblock %}






{% include 'footer.html' %}


<script src="{% static 'styles/js/jquery/jquery-2.2.4.min.js' %}"></script>
<script src="{% static 'styles/js/popper.min.js' %}"></script>
<script src="{% static 'styles/js/bootstrap.min.js' %}"></script>
<script src="{% static 'styles/js/plugins.js' %}"></script>
<script src="{% static 'styles/js/active.js' %}"></script>
    <!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-23581568-13');
</script>


<script defer src="https://static.cloudflareinsights.com/beacon.min.js/vcd15cbe7772f49c399c6a5babf22c1241717689176015" integrity="sha512-ZpsOmlRQV6y907TI0dKBHq9Md29nnaEIPlkf84rnaERnq6zvWvPUqr2ft8M1aS28oN72PdrCzSjY4U6VaAw1EQ==" data-cf-beacon='{"rayId":"918f69f0cbb32d75","version":"2025.1.0","serverTiming":{"name":{"cfExtPri":true,"cfL4":true,"cfSpeedBrain":true,"cfCacheStatus":true}},"token":"cd0b4b3a733644fc843ef0b185f98241","b":1}' crossorigin="anonymous"></script>
</body>
</html>

templates/blog.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<!-- ***** Breadcumb Area Start ***** -->
<section class="breadcumb-area bg-img gradient-background-overlay"
         style="background-image: url({% static 'img/bg-img/breadcumb2.jpg' %});">
    <div class="container h-100">
        <div class="row h-100 align-items-center">
            <div class="col-12">
                <div class="breadcumb-content">
                    <h3 class="breadcumb-title">Hospitals</h3>
                    <p>Lorem ipsum dolor sit amet, consectetuer</p>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- ***** Breadcumb Area End ***** -->

<!-- ***** Blog Area Start ***** -->
<section class="medilife-blog-area section-padding-100">
    <div class="container">
        <div class="row">
            <div class="col-12 col-lg-8">
                <div class="row">
                    <!-- Single Blog Area -->
                    {% for hospital in hospitals %}
                    <div class="col-12 col-md-6">
                        <div class="single-blog-area bg-gray mb-50">
                            <!-- Post Thumbnail -->
                            <div class="blog-post-thumbnail">

                                <img src="{{ hospital.hospital_image.first.image.url }}" alt="Hospital Image">
                                <!-- Post Date -->
                                <div class="post-date">
                                    <a href="{% url 'hospital:hospital_detail' hospital.slug %}">{{ hospital.region }}</a>
                                </div>
                            </div>
                            <!-- Post Content -->
                            <div class="post-content">
                                <div class="post-author">
<!--                                    <a href="#"><img src="{% static 'img/blog-img/p1.jpg' %}" alt=""></a>-->
                                </div>
                                <a href="{% url 'hospital:hospital_detail' hospital.slug %}" class="headline">{{ hospital.name }}</a>
                                <p>{{ hospital.description }}</p>
                                <a href="{% url 'hospital:hospital_detail' hospital.slug %}" class="comments"> {{ hospital.phone }}</a>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>

            <div class="col-12 col-lg-4">
                <div class="medilife-blog-sidebar-area">

                    <!-- Search Widget -->
                    <div class="search-widget-area mb-50">
                        <form action="#" method="get">
                            <input type="search" placeholder="Type Any Keywords">
                            <input type="submit" value="Search">
                        </form>
                    </div>

                    <!-- Catagories Widget -->
                    <div class="medilife-catagories-card mb-50">
                        <h5>Categories</h5>
                        <ul class="catagories-menu">
                            <li><a href="#">Radiology</a></li>
                            <li><a href="#">Cardiology</a></li>
                            <li><a href="#">Gastroenterology</a></li>
                            <li><a href="#">Neurology</a></li>
                            <li><a href="#">General surgery</a></li>
                        </ul>
                    </div>

                    <!-- Latest News -->
                    <div class="latest-news-widget-area mb-50">
                        <h5>Latest News</h5>
                        <div class="widget-blog-post">
                            <!-- Single Blog Post -->
                            <div class="widget-single-blog-post d-flex align-items-center">
                                <div class="widget-post-thumbnail pr-3">
                                    <img src="media/img/blog-img/ln1.jpg" alt="">
                                </div>
                                <div class="widget-post-content">
                                    <a href="#">A big discovery for medicine</a>
                                    <p>Dec 02, 2017</p>
                                </div>
                            </div>
                            <!-- Single Blog Post -->
                            <div class="widget-single-blog-post d-flex align-items-center">
                                <div class="widget-post-thumbnail pr-3">
                                    <img src="media/img/blog-img/ln2.jpg" alt="">
                                </div>
                                <div class="widget-post-content">
                                    <a href="#">Dentistry for everybody</a>
                                    <p>Dec 02, 2017</p>
                                </div>
                            </div>
                            <!-- Single Blog Post -->
                            <div class="widget-single-blog-post d-flex align-items-center">
                                <div class="widget-post-thumbnail pr-3">
                                    <img src="media/img/blog-img/ln3.jpg" alt="">
                                </div>
                                <div class="widget-post-content">
                                    <a href="#">When it’s time to take pills</a>
                                    <p>Dec 02, 2017</p>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- medilife Emergency Card -->
                    <div class="medilife-emergency-card bg-img bg-overlay"
                         style="background-image: url(media/img/bg-img/about1.jpg);">
                        <i class="icon-smartphone"></i>
                        <h2>For Emergency calls</h2>
                        <h3>+12-823-611-8721</h3>
                    </div>

                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <!-- Pagination Area -->
                <div class="pagination-area mt-50">
                    <nav aria-label="Page navigation">
                        <ul class="pagination">
                            <li class="page-item"><a class="page-link" href="#">01</a></li>
                            <li class="page-item active"><a class="page-link" href="#">02</a></li>
                            <li class="page-item"><a class="page-link" href="#">03</a></li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- ***** Blog Area End ***** -->

{% endblock %}

templates/footer.html
{% load static %}

    <footer class="footer-area section-padding-100">
        <!-- Main Footer Area -->
        <div class="main-footer-area">
            <div class="container-fluid">
                <div class="row">

                    <div class="col-12 col-sm-6 col-xl-3">
                        <div class="footer-widget-area">
                            <div class="footer-logo">
                                <img src="media/img/core-img/logo.png" alt="">
                            </div>
                            <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Lorem ipsum dolor sit amet, consectetuer.</p>
                            <div class="footer-social-info">
                                <a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a>
                                <a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a>
                                <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                                <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                            </div>
                        </div>
                    </div>

                    <div class="col-12 col-sm-6 col-xl-3">
                        <div class="footer-widget-area">
                            <div class="widget-title">
                                <h6>Latest News</h6>
                            </div>
                            <div class="widget-blog-post">
                                <!-- Single Blog Post -->
                                <div class="widget-single-blog-post d-flex">
                                    <div class="widget-post-thumbnail">
                                        <img src="media/img/blog-img/ln1.jpg" alt="">
                                    </div>
                                    <div class="widget-post-content">
                                        <a href="#">Better Health Care</a>
                                        <p>Dec 02, 2017</p>
                                    </div>
                                </div>
                                <!-- Single Blog Post -->
                                <div class="widget-single-blog-post d-flex">
                                    <div class="widget-post-thumbnail">
                                        <img src="media/img/blog-img/ln2.jpg" alt="">
                                    </div>
                                    <div class="widget-post-content">
                                        <a href="#">A new drug is tested</a>
                                        <p>Dec 02, 2017</p>
                                    </div>
                                </div>
                                <!-- Single Blog Post -->
                                <div class="widget-single-blog-post d-flex">
                                    <div class="widget-post-thumbnail">
                                        <img src="media/img/blog-img/ln3.jpg" alt="">
                                    </div>
                                    <div class="widget-post-content">
                                        <a href="#">Health department advice</a>
                                        <p>Dec 02, 2017</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-12 col-sm-6 col-xl-3">
                        <div class="footer-widget-area">
                            <div class="widget-title">
                                <h6>Contact Form</h6>
                            </div>
                            <div class="footer-contact-form">
                                <form action="#" method="post">
                                    <input type="text" class="form-control border-top-0 border-right-0 border-left-0" name="footer-name" id="footer-name" placeholder="Name">
                                    <input type="email" class="form-control border-top-0 border-right-0 border-left-0" name="footer-email" id="footer-email" placeholder="Email">
                                    <textarea name="message" class="form-control border-top-0 border-right-0 border-left-0" id="footerMessage" placeholder="Message"></textarea>
                                    <button type="submit" class="btn medilife-btn">Contact Us <span>+</span></button>
                                </form>
                            </div>
                        </div>
                    </div>

                    <div class="col-12 col-sm-6 col-xl-3">
                        <div class="footer-widget-area">
                            <div class="widget-title">
                                <h6>News Letter</h6>
                            </div>

                            <div class="footer-newsletter-area">
                                <form action="#">
                                    <input type="email" class="form-control border-0 mb-0" name="newsletterEmail" id="newsletterEmail" placeholder="Your Email Here">
                                    <button type="submit">Subscribe</button>
                                </form>
                                <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Lorem ipsum dolor sit amet, consectetuer.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Bottom Footer Area -->
        <div class="bottom-footer-area">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="bottom-footer-content">
                            <!-- Copywrite Text -->
                            <div class="copywrite-text">
                                <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com/" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>

templates/google_map.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <h1>Hospital Locations</h1>
    <div id="map" style="width: 100%; height: 600px;"></div>

    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB0mA9uPGKVwKi4GOXDMGDWESAYwR5JxkE"></script>
    <script>
    function initMap() {
        var center = JSON.parse('{{ map_center|safe }}');  // Backend-dan kelgan markaz
        var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 12,
            center: center
        });

            // JSON ma'lumotlarini to'g'ri formatda olish
            var hospitals = {{ hospitals_json|safe }};

            hospitals.forEach(hospital => {
                if (hospital.latitude && hospital.longitude) {
                    var marker = new google.maps.Marker({
                        position: {lat: parseFloat(hospital.latitude), lng: parseFloat(hospital.longitude)},
                        map: map,
                        title: hospital.name
                    });

                    var infowindow = new google.maps.InfoWindow({
                        content: `<h3>${hospital.name}</h3><p>${hospital.address}</p>
                                  <a href="https://www.google.com/maps?q=${hospital.latitude},${hospital.longitude}" target="_blank">
                                  Google Maps-da ko'rish</a>`
                    });

                    marker.addListener('click', function() {
                        infowindow.open(map, marker);
                    });
                }
            });
        }
    </script>
{% endblock %}

templates/navbar.html
{% load static %}
{% load navbar %}
{% navbar as regions %}

<!-- Preloader -->
<div id="preloader">
    <div class="medilife-load"></div>
</div>

<!-- ***** Header Area Start ***** -->
<header class="header-area">
    <!-- Top Header Area -->
    <div class="top-header-area">
        <div class="container h-100">
            <div class="row h-100">
                <div class="col-12 h-100">
                    <div class="h-100 d-md-flex justify-content-between align-items-center">
                        <p>Welcome to <span>MedLine</span></p>
                        <p>Opening Hours : Monday to Saturday - 8am to 10pm Contact : <span>+998 91 250 75 95</span></p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Main Header Area -->
    <div class="main-header-area" id="stickyHeader">
        <div class="container h-100">
            <div class="row h-100 align-items-center">
                <div class="col-12 h-100">
                    <div class="main-menu h-100">
                        <nav class="navbar h-100 navbar-expand-lg">
                            <!-- Logo Area  -->
                            <a class="navbar-brand" href="index.html"><img src="{% static '/img/core-img/logo.png' %}"
                                                                           alt="Logo"></a>


                            <div class="collapse navbar-collapse" id="medilifeMenu">
                                <!-- Menu Area -->
                                <ul class="navbar-nav ml-auto">
                                    <li class="nav-item">
                                        <a class="nav-link" href="{% url 'hospital:home' %}">Home <span
                                                class="sr-only"></span></a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="about-us.html">About Us</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="{% url 'hospital:hospital_list' %}">Hospital</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="{% url 'hospital:hospital_map_list' %}">Hospital_Map</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href=".">Services</a>
                                    </li>
                                    <li class="nav-item ">
                                        <a class="nav-link" href=".">News</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href=".">Contact</a>
                                    </li>
                                </ul>
                                <!-- Appointment Button -->

                                <div class="dropdown">
                                    <button class="btn medilife-appoint-btn ml-30 dropdown-toggle" type="button"
                                            id="regionDropdown"
                                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <span id="selectedRegion">Region</span>
                                    </button>
                                    <div class="dropdown-menu" aria-labelledby="regionDropdown">
                                        {% for region in regions %}
                                        <a class="dropdown-item region-item" href="#" data-region="{{ region.name }}">
                                            {{ region.name }}</a>
                                        {% endfor %}
                                    </div>
                                </div>
                                <script>
                                    document.addEventListener("DOMContentLoaded", function () {
                                        const regionItems = document.querySelectorAll(".region-item");
                                        const selectedRegion = document.getElementById("selectedRegion");

                                        // LocalStorage dan avvalgi tanlangan regionni olish
                                        const savedRegion = localStorage.getItem("selectedRegion");
                                        if (savedRegion) {
                                            selectedRegion.textContent = savedRegion;
                                        }

                                        // Region tanlanganida URL`ni yangilash va LocalStorage`ga saqlash
                                        regionItems.forEach(item => {
                                            item.addEventListener("click", function (event) {
                                                event.preventDefault();
                                                const regionName = this.getAttribute("data-region");
                                                selectedRegion.textContent = regionName;
                                                localStorage.setItem("selectedRegion", regionName);

                                                // URL`ni yangilash
                                                const currentUrl = new URL(window.location);
                                                currentUrl.searchParams.set('region', regionName);
                                                window.location.href = currentUrl.toString();  // Sahifani yangilash
                                            });
                                        });
                                    });
                                </script>


                            </div>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- ***** Header Area End ***** -->